include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    always_declare_return_types: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    one_member_abstracts: true
    only_throw_errors: false
    package_api_docs: true
    prefer_final_in_for_each: true
    use_build_context_synchronously: false
    file_names: false
    library_private_types_in_public_api: false
    inference_failure_on_function_invocation: false

analyzer:
  language:
    # immature and causes false positives
    strict-inference: false
    strict-raw-types: true
  exclude:
    - lib/ffi/*
  errors:
    invalid_assignment: warning
    missing_return: error
    dead_code: info
    todo: ignore
