include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    always_declare_return_types: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    one_member_abstracts: true
    only_throw_errors: true
    package_api_docs: true
    prefer_final_in_for_each: true

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  exclude:
    - lib/bridge_generated.dart
    - lib/bridge_generated.io.dart
    - lib/bridge_generated.web.dart
    - lib/bridge_definitions.dart
  errors:
    invalid_assignment: warning
    missing_return: error
    dead_code: info
