name: playback
description: Showcase App for Fluent UI package for Flutter
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  clipboard: ^0.1.3
  ffi: ^2.0.1
  fluent_ui: ^4.1.2
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.0.0+2
  flutter_markdown: ^0.6.10+5
  flutter_native_splash: ^2.1.6
  flutter_rust_bridge: 1.54.0
  flutter_syntax_view:
    git:
      url: https://github.com/YehudaKremer/flutter_syntax_view.git
  flutter_tabler_icons: ^1.1.2
  http: ^0.13.4
  provider: ^6.0.3
  system_theme: ^2.0.0
  url_launcher: ^6.1.5
  url_strategy: ^0.2.0
  window_manager: ^0.2.7

dev_dependencies:
  build_runner: ^2.3.2
  ffigen: ^6.0.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/Rubik/Rubik-BlackItalic.ttf
          weight: 900
          style: italic

flutter_native_splash:
  color: "#42a5f5"
  image: assets/flutter_logo.png
