name: playback
description: Client for the playback app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ffi: ^2.0.1
  flutter_rust_bridge: ^1.45.0
  fluent_ui: ^4.1.0
  cupertino_icons: ^1.0.5
  collection: ^1.16.0
  fl_chart: ^0.55.2
  flutter_localizations:
    sdk: flutter
  horizontal_data_table: ^4.1.3
  intl: ^0.17.0
  nanoid: ^1.0.0
  path_provider: ^2.0.11
  provider: ^6.0.4
  timer_builder: ^2.0.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^6.0.1

flutter:
  generate: true
  uses-material-design: true
