name: playback
description: Showcase App for Fluent UI package for Flutter

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1
  flutter_rust_bridge: 1.54.0
  fluent_ui: ^4.1.2
  provider: ^6.0.3
  system_theme: ^2.0.0
  window_manager: ^0.2.7
  flutter_acrylic: ^1.0.0+2
  url_strategy: ^0.2.0
  url_launcher: ^6.1.5
  clipboard: ^0.1.3
  email_validator: ^2.0.1
  http: ^0.13.4
  flutter_markdown: ^0.6.10+5
  flutter_syntax_view:
    git:
      url: https://github.com/YehudaKremer/flutter_syntax_view.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  flutter_lints: ^2.0.0
  ffigen: ^6.0.1
  build_runner: ^2.3.2

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: tabler-icons
      fonts:
        - asset: assets/fonts/tabler-icons.ttf
          style: normal
          weight: 400

flutter_native_splash:
  color: "#42a5f5"
  image: web/assets/flutter_logo.png
