name: Dart Flutter Lints

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "11.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Set Workinng Directory
        run: cd client

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Flutter Lints
        run: flutter analyze
