name: Rust Lints

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    name: Clippy lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Install Rust Nightly Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          default: true
          components: clippy, rustfmt

      - name: Run Cargo Clippy
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          toolchain: nightly
          command: clippy
          args: --all-targets --all-features -- -D clippy::await_holding_refcell_ref -D clippy::missing_safety_doc -D clippy::undocumented_unsafe_blocks
